package uptodate;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import static uptodate.HomePage.DB_URL;
import static uptodate.Reminder.*;
import static uptodate.User.DB_URL;
import static uptodate.User.conn;
import static uptodate.User.stmt;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jenniferluong
 */
public class MainJFrame extends javax.swing.JFrame {

    static String USER = "jen";
    static String PASS = "jen";
    static String DBNAME = "uptodate1";
    static final String JDBC_DRIVER = "org.apache.derby.jdbc.ClientDriver";
    static String DB_URL = "jdbc:derby://localhost:1527/";
    static Connection conn;
    static Statement stmt;

    static String USERNAME = "";
    static String PASSWORD = "";

    static boolean signedIn = false;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_EditUsername = new javax.swing.JDialog();
        JP_EditUsername = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        EditUsername_Input1 = new javax.swing.JTextField();
        EditUsername_OK1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        UsernameEdit_Error1 = new javax.swing.JLabel();
        JD_EditPassword = new javax.swing.JDialog();
        JP_EditUsername1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        EditUsername_Input2 = new javax.swing.JTextField();
        EditUsername_OK2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        UsernameEdit_Error2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Welcome = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JTUsername1 = new javax.swing.JTextField();
        JPWPass = new javax.swing.JPasswordField();
        JBSignIn = new javax.swing.JButton();
        JBCreateAccount = new javax.swing.JButton();
        JLError1 = new javax.swing.JLabel();
        User = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JLUsername = new javax.swing.JLabel();
        JLPassword = new javax.swing.JLabel();
        JB_EditUsername = new javax.swing.JButton();
        JB_EditPassword = new javax.swing.JButton();
        CreateAcct = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPFPassword = new javax.swing.JPasswordField();
        JTUsername = new javax.swing.JTextField();
        JBCreateAcct = new javax.swing.JButton();
        JLError = new javax.swing.JLabel();
        JBCreateAcct1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        Homepage = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        JD_EditUsername.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        JD_EditUsername.setTitle("Edit Username");
        JD_EditUsername.setBackground(new java.awt.Color(255, 255, 255));

        JP_EditUsername.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel17.setText("Update:");

        EditUsername_Input1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        EditUsername_Input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditUsername_Input1ActionPerformed(evt);
            }
        });

        EditUsername_OK1.setText("OK");
        EditUsername_OK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditUsername_OK1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel6.setText("Change username to:");

        UsernameEdit_Error1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        javax.swing.GroupLayout JP_EditUsernameLayout = new javax.swing.GroupLayout(JP_EditUsername);
        JP_EditUsername.setLayout(JP_EditUsernameLayout);
        JP_EditUsernameLayout.setHorizontalGroup(
            JP_EditUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_EditUsernameLayout.createSequentialGroup()
                .addGroup(JP_EditUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_EditUsernameLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel6))
                    .addGroup(JP_EditUsernameLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(EditUsername_Input1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JP_EditUsernameLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(UsernameEdit_Error1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_EditUsernameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EditUsername_OK1)
                .addGap(102, 102, 102))
        );
        JP_EditUsernameLayout.setVerticalGroup(
            JP_EditUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_EditUsernameLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(UsernameEdit_Error1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JP_EditUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(EditUsername_Input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditUsername_OK1)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout JD_EditUsernameLayout = new javax.swing.GroupLayout(JD_EditUsername.getContentPane());
        JD_EditUsername.getContentPane().setLayout(JD_EditUsernameLayout);
        JD_EditUsernameLayout.setHorizontalGroup(
            JD_EditUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_EditUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        JD_EditUsernameLayout.setVerticalGroup(
            JD_EditUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_EditUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        JD_EditPassword.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        JD_EditPassword.setTitle("Edit Username");
        JD_EditPassword.setBackground(new java.awt.Color(255, 255, 255));

        JP_EditUsername1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel18.setText("Update:");

        EditUsername_Input2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        EditUsername_Input2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditUsername_Input2ActionPerformed(evt);
            }
        });

        EditUsername_OK2.setText("OK");
        EditUsername_OK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditUsername_OK2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel13.setText("Change username to:");

        UsernameEdit_Error2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        javax.swing.GroupLayout JP_EditUsername1Layout = new javax.swing.GroupLayout(JP_EditUsername1);
        JP_EditUsername1.setLayout(JP_EditUsername1Layout);
        JP_EditUsername1Layout.setHorizontalGroup(
            JP_EditUsername1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_EditUsername1Layout.createSequentialGroup()
                .addGroup(JP_EditUsername1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_EditUsername1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel13))
                    .addGroup(JP_EditUsername1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(EditUsername_Input2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JP_EditUsername1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(UsernameEdit_Error2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_EditUsername1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EditUsername_OK2)
                .addGap(102, 102, 102))
        );
        JP_EditUsername1Layout.setVerticalGroup(
            JP_EditUsername1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_EditUsername1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(UsernameEdit_Error2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JP_EditUsername1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(EditUsername_Input2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditUsername_OK2)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout JD_EditPasswordLayout = new javax.swing.GroupLayout(JD_EditPassword.getContentPane());
        JD_EditPassword.getContentPane().setLayout(JD_EditPasswordLayout);
        JD_EditPasswordLayout.setHorizontalGroup(
            JD_EditPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_EditUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        JD_EditPasswordLayout.setVerticalGroup(
            JD_EditPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_EditUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("up to date");
        setPreferredSize(new java.awt.Dimension(500, 400));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setLayout(new java.awt.CardLayout());

        Welcome.setBackground(new java.awt.Color(255, 255, 255));
        Welcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Mark My Words", 1, 60)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("UpToDate");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Welcome.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 100));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel8.setText("Username:");
        Welcome.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 20));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel9.setText("Password:");
        Welcome.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        JTUsername1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        JTUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTUsername1ActionPerformed(evt);
            }
        });
        Welcome.add(JTUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 135, -1));

        JPWPass.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        JPWPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPWPassActionPerformed(evt);
            }
        });
        Welcome.add(JPWPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 136, -1));

        JBSignIn.setBackground(new java.awt.Color(255, 255, 255));
        JBSignIn.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        JBSignIn.setText("Sign In");
        JBSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSignInActionPerformed(evt);
            }
        });
        Welcome.add(JBSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        JBCreateAccount.setBackground(new java.awt.Color(255, 255, 255));
        JBCreateAccount.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        JBCreateAccount.setText("Create an Account");
        JBCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCreateAccountActionPerformed(evt);
            }
        });
        Welcome.add(JBCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        JLError1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        JLError1.setForeground(new java.awt.Color(204, 0, 51));
        JLError1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome.add(JLError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 190, 20));

        jPanel3.add(Welcome, "card3");

        User.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Mark My Words", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User Information");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setText("Password:");

        JLUsername.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        JLUsername.setText("[username]");

        JLPassword.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        JLPassword.setText("[password]");

        JB_EditUsername.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        JB_EditUsername.setText("Edit");
        JB_EditUsername.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JB_EditUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_EditUsernameActionPerformed(evt);
            }
        });

        JB_EditPassword.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        JB_EditPassword.setText("Edit");

        javax.swing.GroupLayout UserLayout = new javax.swing.GroupLayout(User);
        User.setLayout(UserLayout);
        UserLayout.setHorizontalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(UserLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(JLPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(UserLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(JLUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_EditUsername)
                    .addComponent(JB_EditPassword))
                .addGap(104, 104, 104))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UserLayout.setVerticalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JLUsername)
                    .addComponent(JB_EditUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JLPassword)
                    .addComponent(JB_EditPassword))
                .addGap(199, 199, 199))
        );

        jPanel3.add(User, "card2");

        CreateAcct.setBackground(new java.awt.Color(255, 255, 255));
        CreateAcct.setForeground(new java.awt.Color(0, 51, 102));
        CreateAcct.setMaximumSize(new java.awt.Dimension(320, 327));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Create an Account");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel11.setText("Username:");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel12.setText("Password:");

        jPFPassword.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jPFPassword.setSize(new java.awt.Dimension(135, 26));
        jPFPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPFPasswordActionPerformed(evt);
            }
        });

        JTUsername.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        JBCreateAcct.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        JBCreateAcct.setText("Create");
        JBCreateAcct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCreateAcctActionPerformed(evt);
            }
        });

        JLError.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        JLError.setForeground(new java.awt.Color(204, 0, 51));
        JLError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        JBCreateAcct1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        JBCreateAcct1.setText("Go Back");
        JBCreateAcct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCreateAcct1ActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Mark My Words", 1, 60)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("UpToDate");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout CreateAcctLayout = new javax.swing.GroupLayout(CreateAcct);
        CreateAcct.setLayout(CreateAcctLayout);
        CreateAcctLayout.setHorizontalGroup(
            CreateAcctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CreateAcctLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(CreateAcctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateAcctLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(JTUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreateAcctLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jPFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreateAcctLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(JBCreateAcct1)
                        .addGap(30, 30, 30)
                        .addComponent(JBCreateAcct)))
                .addContainerGap(147, Short.MAX_VALUE))
            .addComponent(JLError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CreateAcctLayout.setVerticalGroup(
            CreateAcctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateAcctLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLError, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(CreateAcctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(JTUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreateAcctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jPFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(CreateAcctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBCreateAcct)
                    .addComponent(JBCreateAcct1))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jPanel3.add(CreateAcct, "card4");

        Homepage.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Mark My Words", 1, 60)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 102));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("UpToDate");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout HomepageLayout = new javax.swing.GroupLayout(Homepage);
        Homepage.setLayout(HomepageLayout);
        HomepageLayout.setHorizontalGroup(
            HomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        HomepageLayout.setVerticalGroup(
            HomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomepageLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 278, Short.MAX_VALUE))
        );

        jPanel3.add(Homepage, "card5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("Account");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem1.setText("View Account");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Appointment");
        jMenu3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem5.setText("View");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem2.setText("Create");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem3.setText("Edit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem4.setText("Delete");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Settings");
        jMenu4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jMenu6.setText("Calendar Appearance");
        jMenu6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jMenu7.setText("Range");
        jMenu7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem6.setText("Day");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem7.setText("Week");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem8.setText("Month");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        jMenu6.add(jMenu7);

        jMenu8.setText("Color");
        jMenu8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jMenuItem15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem15.setText("Red");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem15);

        jMenuItem16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem16.setText("Green");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem16);

        jMenuItem17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem17.setText("Blue");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem17);

        jMenu6.add(jMenu8);

        jMenu4.add(jMenu6);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Help");
        jMenu5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        //removes all panels
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        //adds create account panel
        jPanel3.add(User);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jPFPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPFPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPFPasswordActionPerformed

    private void JBCreateAcctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCreateAcctActionPerformed
        // TODO add your handling code here:
        USERNAME = JTUsername.getText();
        PASSWORD = String.valueOf(jPFPassword.getPassword());

        System.out.println("USERNAME: " + USERNAME);
        System.out.println("PASSWORD: " + PASSWORD);

        DB_URL = DB_URL + DBNAME + ";user=" + USER + ";password=" + PASS;
        Connection conn = null; //initialize the connection
        Statement stmt = null;  //initialize the statement that we're using

        try {
            //STEP 2: Register JDBC driver
            Class.forName ("org.apache.derby.jdbc.ClientDriver");

            //STEP 3: Open a connection
            System.out.println("Connecting to database...");
            conn = DriverManager.getConnection(DB_URL);

            PreparedStatement ps = null;
            String sql = "SELECT * FROM \"USER\" WHERE LOWER(username) = LOWER(?)";
            ps = conn.prepareStatement(sql);
            ps.setString(1, USERNAME);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                System.out.println("True");
                JLError.setText("Error. Try a different username.");
                USERNAME = JTUsername.getText();
                ps.setString(1, USERNAME);
                rs = ps.executeQuery();
            } 
            else {
                PreparedStatement pstmt = null;
                String sql1 = "INSERT INTO \"USER\" (username, password) VALUES (?,?)";
                pstmt = conn.prepareStatement(sql1);
                pstmt.setString(1, USERNAME);
                pstmt.setString(2, USERNAME);
                pstmt.executeUpdate();

                System.out.println("W00t");
                
                //removes all panels
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                //adds create account panel
                jPanel3.add(Homepage);
                jPanel3.repaint();
                jPanel3.revalidate();
                
                JLUsername.setText(USERNAME);
                JLPassword.setText(PASSWORD);
            }

        } catch (SQLException se) {
            se.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (stmt != null) {
                    stmt.close();
                }
            } catch (SQLException se2) {
            }
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
        
        
    }//GEN-LAST:event_JBCreateAcctActionPerformed

    private void JBCreateAcct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCreateAcct1ActionPerformed
        // TODO add your handling code here:
        
        //removes all panels
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        //adds create account panel
        jPanel3.add(Welcome);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_JBCreateAcct1ActionPerformed

    private void JB_EditUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_EditUsernameActionPerformed
        // TODO add your handling code here:
        JD_EditUsername.setVisible (true);        
    }//GEN-LAST:event_JB_EditUsernameActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void JBCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCreateAccountActionPerformed
        // TODO add your handling code here:

        //removes all panels
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        //adds create account panel
        jPanel3.add(CreateAcct);
        jPanel3.repaint();
        jPanel3.revalidate();

    }//GEN-LAST:event_JBCreateAccountActionPerformed

    private void JBSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSignInActionPerformed
        // TODO add your handling code here:
        USERNAME = JTUsername1.getText();
        PASSWORD = String.valueOf(JPWPass.getPassword());

        System.out.println("USERNAME: " + USERNAME);
        System.out.println("PASSWORD: " + PASSWORD);

        DB_URL = DB_URL + DBNAME + ";user=" + USER + ";password=" + PASS;
        Connection conn = null; //initialize the connection
        Statement stmt = null;  //initialize the statement that we're using
        try {
            //STEP 2: Register JDBC driver
            Class.forName("org.apache.derby.jdbc.ClientDriver");

            //STEP 3: Open a connection
            System.out.println("Connecting to database...");
            conn = DriverManager.getConnection(DB_URL);

            PreparedStatement ps = null;
            String signIn = "select username, password from \"USER\" where username = ? and password = ?";
            ps = conn.prepareStatement(signIn);
            ps.setString(1, USERNAME);
            ps.setString(2, PASSWORD);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {

                System.out.println("True");
                signedIn = true;
                //removes all panels
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                //adds create account panel
                jPanel3.add(Homepage);
                jPanel3.repaint();
                jPanel3.revalidate();

                JLUsername.setText(USERNAME);
                JLPassword.setText(PASSWORD);

            } else {
                JLError1.setText("Error. Wrong information.");
                Welcome.repaint();
                Welcome.revalidate();

                USERNAME = JTUsername1.getText();
                PASSWORD = String.valueOf(JPWPass.getPassword());
            }
        } catch (SQLException se) {
            se.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (stmt != null) {
                    stmt.close();
                }
            } catch (SQLException se2) {
            }
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
    }//GEN-LAST:event_JBSignInActionPerformed

    private void JPWPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPWPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPWPassActionPerformed

    private void JTUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTUsername1ActionPerformed

    private void EditUsername_Input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditUsername_Input1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditUsername_Input1ActionPerformed

    private void EditUsername_OK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditUsername_OK1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditUsername_OK1ActionPerformed

    private void EditUsername_Input2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditUsername_Input2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditUsername_Input2ActionPerformed

    private void EditUsername_OK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditUsername_OK2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditUsername_OK2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new MainJFrame().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateAcct;
    private javax.swing.JTextField EditUsername_Input1;
    private javax.swing.JTextField EditUsername_Input2;
    private javax.swing.JButton EditUsername_OK1;
    private javax.swing.JButton EditUsername_OK2;
    private javax.swing.JPanel Homepage;
    private javax.swing.JButton JBCreateAccount;
    private javax.swing.JButton JBCreateAcct;
    private javax.swing.JButton JBCreateAcct1;
    private javax.swing.JButton JBSignIn;
    private javax.swing.JButton JB_EditPassword;
    private javax.swing.JButton JB_EditUsername;
    private javax.swing.JDialog JD_EditPassword;
    private javax.swing.JDialog JD_EditUsername;
    private javax.swing.JLabel JLError;
    private javax.swing.JLabel JLError1;
    private javax.swing.JLabel JLPassword;
    private javax.swing.JLabel JLUsername;
    private javax.swing.JPasswordField JPWPass;
    private javax.swing.JPanel JP_EditUsername;
    private javax.swing.JPanel JP_EditUsername1;
    private javax.swing.JTextField JTUsername;
    private javax.swing.JTextField JTUsername1;
    private javax.swing.JPanel User;
    private javax.swing.JLabel UsernameEdit_Error1;
    private javax.swing.JLabel UsernameEdit_Error2;
    private javax.swing.JPanel Welcome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPasswordField jPFPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
